const messagesEl=document.getElementById("messages"),formEl=document.getElementById("chatForm"),inputEl=document.getElementById("messageInput"),newChatBtn=document.getElementById("newChatBtn"),newChatMirror=document.getElementById("newChatMirror"),exportPdfBtn=document.getElementById("exportPdfBtn"),pdfModal=document.getElementById("pdfModal"),pdfEditor=document.getElementById("pdfEditor"),closePdfModal=document.getElementById("closePdfModal"),downloadPdfBtn=document.getElementById("downloadPdfBtn"),chatListEl=document.getElementById("chatList"),chatSearchEl=document.getElementById("chatSearch"),pinChatBtn=document.getElementById("pinChatBtn"),renameChatBtn=document.getElementById("renameChatBtn"),deleteChatBtn=document.getElementById("deleteChatBtn");
const API_ENDPOINT=window.NEXUS_API_ENDPOINT||"/api/chat",STORAGE_KEY="nexus_rx_chats_v5";
let chats=loadChats(),currentChatId=null,conversation=[],activeTool="";
function uid(){return"chat_"+Date.now()+"_"+Math.random().toString(16).slice(2)}
function loadChats(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function saveChats(){localStorage.setItem(STORAGE_KEY,JSON.stringify(chats))}
function getCurrentChat(){return chats.find(c=>c.id===currentChatId)}
function createChat(title="New Chat"){const chat={id:uid(),title,pinned:false,messages:[],createdAt:Date.now(),updatedAt:Date.now()};chats.unshift(chat);currentChatId=chat.id;conversation=[];saveChats();renderChatList();renderMessages()}
function updateChat(){const chat=getCurrentChat();if(!chat)return;chat.messages=conversation;chat.updatedAt=Date.now();if(chat.title==="New Chat"){const first=conversation.find(m=>m.role==="user")?.content||"";if(first)chat.title=cleanDisplay(first).slice(0,42)}saveChats();renderChatList()}
function renderChatList(){const q=(chatSearchEl.value||"").toLowerCase();chatListEl.innerHTML="";chats.filter(c=>!q||c.title.toLowerCase().includes(q)).sort((a,b)=>(b.pinned-a.pinned)||b.updatedAt-a.updatedAt).forEach(chat=>{const b=document.createElement("button");b.className="history-item"+(chat.id===currentChatId?" active":"");b.innerHTML=`<div class="history-title">${chat.pinned?"★ ":""}${escapeHtml(chat.title)}</div><div class="history-date">${new Date(chat.updatedAt).toLocaleDateString()}</div>`;b.onclick=()=>{currentChatId=chat.id;conversation=[...chat.messages];renderChatList();renderMessages()};chatListEl.appendChild(b)})}
function escapeHtml(s=""){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function cleanDisplay(s=""){return stripHtml(String(s||"")).replace(/^@(case|compare|reverse|report|safety)\s*/i,"").trim()||s}
function stripHtml(s=""){return String(s||"").replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<\/?[^>]+>/g,"").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'")}
function autoGrow(el){el.style.height="auto";el.style.height=Math.min(el.scrollHeight,160)+"px"}
function normalizeCommand(t){if(activeTool&&!/^@/.test(t.trim()))return activeTool+t;return t.replace(/^\/قارن\s+/i,"@compare ").replace(/^\/عكس\s+/i,"@reverse ").replace(/^\/تقرير\s*/i,"@report ")}
function isGreeting(t=""){return/^(hi|hello|hey|اهلا|أهلا|هاي|سلام|السلام عليكم)\s*[!.؟]*$/i.test(t.trim())}
function isCommandOnly(t=""){return/^@(case|compare|reverse|report|safety)\s*$/i.test(t.trim())}
function modeFromText(t=""){t=t.toLowerCase();if(t.startsWith("@compare"))return"comparison_mode";if(t.startsWith("@reverse"))return"reverse_mode";if(t.startsWith("@report"))return"report_mode";if(t.startsWith("@case"))return"case_analysis";if(t.startsWith("@safety"))return"drug_safety";if(/interaction|contraindication|warfarin|amiodarone|safe with|together/i.test(t))return"drug_safety";if(/dose|mechanism|uses|side effect|paracetamol|metformin|ramipril|lisinopril/i.test(t))return"drug_info";if(/patient|serum|creatinine|egfr|potassium|bp|hr|مريض/i.test(t))return"case_analysis";return"general_chat"}
function commandReply(t){t=t.trim().toLowerCase();if(t==="@case")return"Send the case details: age, sex, diagnosis, medications, relevant labs, symptoms, and the exact question.";if(t==="@compare")return"Type the two medicines after the command, for example: @compare ramipril losartan";if(t==="@reverse")return"Type the drug and scenario, for example: @reverse alfuzosin + grapefruit";if(t==="@report")return"Send the case or answer you want converted into an editable report.";if(t==="@safety")return"Send the medicines or medication list you want checked for safety.";return"Send the missing details after the command."}
function inlineMd(s=""){let x=escapeHtml(s);x=x.replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\*([^*]+)\*/g,"<em>$1</em>");return x}
function mdToHtml(md=""){let text=stripHtml(md).trim().replace(/^\s*---+\s*$/gm,"");const blocks=text.split(/\n{2,}/);return blocks.map(block=>{const lines=block.split("\n").filter(Boolean);if(!lines.length)return"";if(lines.length>=2&&lines[0].includes("|")&&/^(\s*\|?\s*:?-{3,}:?\s*\|)+/.test(lines[1])){const h=lines[0].split("|").map(c=>c.trim()).filter(Boolean);const rows=lines.slice(2).map(l=>l.split("|").map(c=>c.trim()).filter(Boolean)).filter(Boolean);return`<table><thead><tr>${h.map(c=>`<th>${inlineMd(c)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${inlineMd(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`}if(/^#{1,3}\s+/.test(block)){const level=Math.min(block.match(/^#+/)[0].length,3);return`<h${level}>${inlineMd(block.replace(/^#{1,3}\s+/,""))}</h${level}>`}if(lines.every(l=>/^\s*[-*]\s+/.test(l)))return`<ul>${lines.map(l=>`<li>${inlineMd(l.replace(/^\s*[-*]\s+/,""))}</li>`).join("")}</ul>`;if(lines.every(l=>/^\s*\d+\.\s+/.test(l)))return`<ol>${lines.map(l=>`<li>${inlineMd(l.replace(/^\s*\d+\.\s+/,""))}</li>`).join("")}</ol>`;return`<p>${inlineMd(lines.join("<br>"))}</p>`}).join("")}
function modeLabel(mode){return mode.replace(/_/g,"-")}
function appendMessage(role,content,mode=""){const wrap=document.createElement("div");wrap.className=`message ${role}`;if(role==="user"){wrap.innerHTML=`<div class="user-bubble">${escapeHtml(cleanDisplay(content)).replace(/\n/g,"<br>")}</div>`}else{wrap.innerHTML=`<div class="assistant-header"><span class="assistant-dot">+</span><span>Nexus Rx · Clinical AI</span><span class="mode-pill pill-${mode||"general_chat"}">${modeLabel(mode||"general_chat")}</span></div><div class="assistant-body">${mdToHtml(content)}</div><div class="disclaimer">Educational decision support only. Verify with primary sources.</div><div class="message-actions"><button data-copy>Copy</button><button data-report>Make report</button><button data-correct>Correct</button></div>`}messagesEl.appendChild(wrap);messagesEl.scrollTop=messagesEl.scrollHeight}
function appendLoading(){const wrap=document.createElement("div");wrap.className="message assistant";wrap.innerHTML=`<div class="loading"><div class="loading-cube"></div><div><strong>Nexus is checking</strong><br><span>Reviewing clinical context...</span></div></div>`;messagesEl.appendChild(wrap);messagesEl.scrollTop=messagesEl.scrollHeight;return wrap}
function renderMessages(){messagesEl.innerHTML="";if(!conversation.length){messagesEl.innerHTML=`<div class="welcome"><div class="welcome-mark">Nx</div><h1>How can I help?</h1><p>Ask about drug data, interactions, protocols, or patient cases. Choose a tool to switch mode.</p></div>`;return}conversation.forEach(m=>appendMessage(m.role,m.content,m.mode||""))}
function cleanModelOutput(t=""){let out=stripHtml(t);out=out.replace(/^\s*prompt the user.*?(?=\n|$)/i,"").replace(/^\s*I need to .*?(?=\n|$)/gim,"").replace(/^\s*I should .*?(?=\n|$)/gim,"").replace(/target=['"]?_blank['"]?/gi,"").replace(/https?:\/\/\S+/gi,"").trim();return out||"Send more details so I can help accurately."}
async function safeJsonResponse(res){const text=await res.text();try{return JSON.parse(text)}catch{throw new Error(text.trim().startsWith("<")?"API route is not returning JSON. Check Vercel /api/chat.":text.slice(0,160))}}
async function submitMessage(raw){const userText=normalizeCommand(raw.trim());if(!userText)return;if(!currentChatId)createChat();conversation.push({role:"user",content:userText});updateChat();renderMessages();let mode=modeFromText(userText);if(isGreeting(userText)||isCommandOnly(userText)){const reply=isGreeting(userText)?"Hi. Send a drug, interaction, or patient case and I’ll help.":commandReply(userText);conversation.push({role:"assistant",content:reply,mode});updateChat();renderMessages();return}const loading=appendLoading();try{const res=await fetch(API_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:conversation})});const data=await safeJsonResponse(res);if(!res.ok)throw new Error(data.error||"AI request failed");mode=data.mode||mode;const reply=cleanModelOutput(data.reply||"");loading.remove();conversation.push({role:"assistant",content:reply,mode});updateChat();renderMessages()}catch(e){loading.remove();conversation.push({role:"assistant",content:"Connection error: "+e.message,mode:"general_chat"});updateChat();renderMessages()}}
formEl.onsubmit=e=>{e.preventDefault();const t=inputEl.value;inputEl.value="";autoGrow(inputEl);submitMessage(t)}
inputEl.oninput=()=>autoGrow(inputEl)
newChatBtn.onclick=newChatMirror.onclick=()=>createChat()
chatSearchEl.oninput=renderChatList
pinChatBtn.onclick=()=>{const c=getCurrentChat();if(!c)return;c.pinned=!c.pinned;saveChats();renderChatList()}
renameChatBtn.onclick=()=>{const c=getCurrentChat();if(!c)return;const n=prompt("Chat name:",c.title);if(n){c.title=n.trim();saveChats();renderChatList()}}
deleteChatBtn.onclick=()=>{if(!currentChatId||!confirm("Delete this chat?"))return;chats=chats.filter(c=>c.id!==currentChatId);currentChatId=chats[0]?.id||null;conversation=getCurrentChat()?.messages||[];saveChats();renderChatList();renderMessages()}
document.querySelectorAll(".tool-tab").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".tool-tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");activeTool=btn.dataset.command||"";inputEl.focus();})
document.addEventListener("click",e=>{if(e.target.matches("[data-copy]"))navigator.clipboard.writeText(conversation.at(-1)?.content||"");if(e.target.matches("[data-report]")){pdfEditor.value=buildReportText();pdfModal.classList.remove("hidden")}if(e.target.matches("[data-correct]")){inputEl.value="Correction: ";inputEl.focus()}})
function buildReportText(){return conversation.map(m=>`${m.role==="user"?"User":"Nexus"}:\n${m.content}`).join("\n\n---\n\n")}
exportPdfBtn.onclick=()=>{pdfEditor.value=buildReportText();pdfModal.classList.remove("hidden")}
closePdfModal.onclick=()=>pdfModal.classList.add("hidden")
downloadPdfBtn.onclick=()=>{const{jsPDF}=window.jspdf;const doc=new jsPDF();const lines=doc.splitTextToSize(pdfEditor.value||buildReportText(),180);let y=16;doc.setFontSize(14);doc.text("Nexus Rx Report",14,y);y+=10;doc.setFontSize(10);lines.forEach(line=>{if(y>280){doc.addPage();y=16}doc.text(line,14,y);y+=5.5});doc.save("nexus-rx-report.pdf");pdfModal.classList.add("hidden")}
if(!chats.length)createChat();else{currentChatId=chats[0].id;conversation=[...(chats[0].messages||[])];renderChatList();renderMessages()}
